mark_open:
  target:
    entity:
      domain: cover
      integration: dooya

mark_closed:
  target:
    entity:
      domain: cover
      integration: dooya

set_known_position:
  target:
    entity:
      domain: cover
      integration: dooya
  fields:
    position:
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider
